import React, { useState, useEffect } from 'react';
import api from '../../services/api';
import ReportDownloadButton from '../../components/reports/ReportDownloadButton';
import AnalysisReportModal from '../../components/hr/AnalysisReportModal';
import './Applications.css';

const Applications = () => {
    const [applications, setApplications] = useState([]);
    const [loading, setLoading] = useState(true);
    const [selectedAnalysis, setSelectedAnalysis] = useState(null);

    useEffect(() => {
        fetchApplications();
    }, []);

    const fetchApplications = async () => {
        try {
            const res = await api.get('applications/my-applications/');
            const data = res.data?.results ?? res.data;
            setApplications(Array.isArray(data) ? data : []);
        } catch (err) {
            console.error("Failed to fetch applications", err);
        } finally {
            setLoading(false);
        }
    };

    const withdrawApplication = async (id) => {
        if (window.confirm("Are you sure you want to withdraw this application? This action cannot be undone.")) {
            try {
                await api.delete(`applications/withdraw/${id}/`);
                fetchApplications();
            } catch (err) {
                console.error("Error withdrawing application:", err);
                alert("Failed to withdraw application.");
            }
        }
    };

    const viewReport = async (appId) => {
        try {
            const res = await api.get(`reports/${appId}/`);
            setSelectedAnalysis(res.data);
        } catch (err) {
            alert('Report is not yet generated by the HR team for this application.');
        }
    };

    if (loading) return <div>Loading applications...</div>;

    return (
        <div className="applications-container">
            <h1 className="page-title">My Applications</h1>

            <div className="applications-list">
                {applications.length === 0 ? (
                    <div className="premium-card">
                        <p>You haven't applied to any jobs yet.</p>
                    </div>
                ) : (
                    applications.map(app => (
                        <div key={app.id} className="premium-card application-card">
                            {/* ── Header ── */}
                            <div className="app-header">
                                <div className="app-job-info">
                                    <h2>{app.job_details?.title}</h2>
                                    <span className="app-company">Location: {app.job_details?.location}</span>
                                </div>
                                <div className={`status-pill status-${app.status.toLowerCase().replace(/\s+/g, '-')}`}>
                                    {app.status}
                                </div>
                            </div>

                            {/* ── Basic details ── */}
                            <div className="app-details">
                                <p><strong>Applied On:</strong> {new Date(app.applied_at).toLocaleDateString()}</p>
                                <p><strong>Resume Used:</strong> {app.resume_details?.file_path ? app.resume_details.file_path.split('/').pop() : 'N/A'}</p>
                            </div>

                            {/* ── Interview details panel ── */}
                            {app.status === 'Interview Scheduled' && app.interview_schedule && (
                                <div className="interview-info-panel mt-3">
                                    <h4 className="interview-panel-title">📅 Your Interview Details</h4>
                                    <div className="interview-info-grid">
                                        <div className="interview-info-item">
                                            <span className="info-label">Date</span>
                                            <span className="info-value">{app.interview_schedule.interview_date}</span>
                                        </div>
                                        <div className="interview-info-item">
                                            <span className="info-label">Time</span>
                                            <span className="info-value">{app.interview_schedule.interview_time}</span>
                                        </div>
                                        <div className="interview-info-item">
                                            <span className="info-label">Mode</span>
                                            <span className="info-value">{app.interview_schedule.interview_mode}</span>
                                        </div>
                                        <div className="interview-info-item">
                                            <span className="info-label">Interviewer</span>
                                            <span className="info-value">{app.interview_schedule.interviewer_name}</span>
                                        </div>
                                        {app.interview_schedule.interview_mode === 'Online' && app.interview_schedule.meeting_link && (
                                            <div className="interview-info-item full-width">
                                                <span className="info-label">Meeting Link</span>
                                                <span className="info-value">
                                                    <a
                                                        href={app.interview_schedule.meeting_link}
                                                        target="_blank"
                                                        rel="noreferrer"
                                                        className="interview-link"
                                                    >
                                                        {app.interview_schedule.meeting_link}
                                                    </a>
                                                </span>
                                            </div>
                                        )}
                                        {app.interview_schedule.interview_mode === 'Offline' && app.interview_schedule.location && (
                                            <div className="interview-info-item full-width">
                                                <span className="info-label">Location</span>
                                                <span className="info-value">{app.interview_schedule.location}</span>
                                            </div>
                                        )}
                                        {app.interview_schedule.notes && (
                                            <div className="interview-info-item full-width">
                                                <span className="info-label">Notes</span>
                                                <span className="info-value">{app.interview_schedule.notes}</span>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            )}

                            {/* ── Actions ── */}
                            <div className="app-actions d-flex gap-2 flex-wrap mt-2">
                                <button
                                    className="btn-small primary"
                                    onClick={() => viewReport(app.id)}
                                >
                                    View Report
                                </button>
                                <ReportDownloadButton
                                    applicationId={app.id}
                                    buttonText="Download PDF Report"
                                    variant="outline"
                                />
                                {app.status === 'Pending' && (
                                    <button
                                        className="btn-small danger ms-auto"
                                        onClick={() => withdrawApplication(app.id)}
                                    >
                                        Withdraw
                                    </button>
                                )}
                            </div>
                        </div>
                    ))
                )}
            </div>

            {selectedAnalysis && (
                <AnalysisReportModal
                    analysis={selectedAnalysis}
                    onClose={() => setSelectedAnalysis(null)}
                />
            )}
        </div>
    );
};

export default Applications;
